export MINTOS_IMAP_USER=
export MINTOS_IMAP_PASSWORD=
export MINTOS_IMAP_HOST=
export MINTOS_IMAP_PORT=
export MINTOS_IMAP_USE_TLS=true
export MINTOS_IMAP_AUTH_TIMEOUT=3000
export MINTOS_IMAP_MARK_AS_READ=true


export MYSQL_HOST=localhost
export MYSQL_USERNAME=
export MYSQL_PASSWORD=
export MYSQL_DATABASE=

node ./index.js
